H_HEADERS=\
src/Utils/CpuInfo.hpp \
src/AgentFactory.hpp \
src/ConstraintFactory.hpp \
src/InputParams.hpp \
src/Preferences.hpp \
src/Problem.hpp \
src/Types.hpp \
src/Variable.hpp \
src/VariableFactory.hpp \
src/Utils/CpuAllocator.hpp \
src/BE/CpuAggregator.hpp \
src/BE/CpuBEAgent.hpp \
src/BE/CpuProjector.hpp \
src/BE/BESolver.hpp \
src/BE/CpuTable.hpp \
src/MiniBE/CpuMiniBEAgent.hpp \

D_HEADERS=\
src/Utils/GpuInfo.cuh \
src/Utils/GpuTimer.cuh \
src/Utils/GpuAllocator.cuh \
src/BE/GpuAggregator.cuh \
src/BE/GpuProjector.cuh \
src/BE/GpuBEAgent.cuh \
src/BE/GpuTable.cuh \
src/MiniBE/GpuMiniBEAgent.cuh